export const site = {
  name: "Agency Name",
  legalName: "",
  companyNumber: "", // Add Companies House number once registered (e.g. "12345678")
  companyJurisdiction: "",
  registeredAddress: "",
  vatNumber: "", // Add if VAT registered (e.g. "GB 123 4567 89"), leave empty if under threshold
  locale: "en-GB",
  regionFocus: "your service area",
  contactEmail: process.env.NEXT_PUBLIC_CONTACT_EMAIL || "",
  phone: "",
  description:
    "Google Ads management and call enquiry tracking for UK trade businesses, in your service area.",
  navigation: [
    { id: "services", href: "/#services", label: "Services" },
    { id: "approach", href: "/#approach", label: "Approach" },
    { id: "about", href: "/#about", label: "About" },
    { id: "contact", href: "/#contact", label: "Get in touch" },
  ],
  headerCta: {
    label: "Get in touch",
    href: "/#contact",
  },
  cta: {
    label: "Get in touch",
    href: "/#contact",
  },
  hero: {
    eyebrow: "Google Ads for UK Trades · Your area",
    heading: "Good work deserves to be found.",
    body: "Targeted Google Ads management and clear call tracking for trade businesses who want more of the right jobs.",
    secondaryCta: {
      label: "See our approach",
      href: "/#approach",
    },
    searchExample: "boiler installation near me",
  },
  servicesEyebrow: "What we do",
  servicesHeading: "Straightforward Google Ads and enquiry tracking.",
  services: [
    {
      id: "google-ads",
      title: "Google Ads management",
      summary:
        "Targeted local search campaigns aimed strictly at the high-margin installation and renovation jobs you actually want.",
      deliverables: [
        "Local radius targeting and negative keywords to stop wasted spend on DIY searches",
        "Clear ad copy matching the exact trade work you offer, without exaggerated claims",
        "Direct billing: advertising spend is always paid directly from your card to Google",
      ],
    },
    {
      id: "call-tracking",
      title: "Call & enquiry tracking",
      summary:
        "Plan how to connect calls and form enquiries to the campaigns that generated them.",
      deliverables: [
        "Call tracking so you know exactly which advert produced the ringing phone",
        "Define and review your own criteria for qualified enquiries",
        "Simple enquiry outcome recording so you can see your real return on investment",
      ],
    },
    {
      id: "performance-reviews",
      title: "Weekly performance reviews",
      summary:
        "Transparent weekly check-ins focused on real enquiries and cost-per-conversation, never vanity impressions.",
      deliverables: [
        "Weekly breakdown of spend, calls received, and quote requests",
        "Ongoing search term cleanup to trim non-converting searches",
        "A clear contact and review process",
      ],
    },
  ],
  approachEyebrow: "Our approach",
  approachHeading: "Simple steps. Shared goals.",
  approachIntro:
    "A straightforward process, built around your trade and your actual capacity.",
  approach: [
    {
      title: "Understand your trade & capacity",
      body: "We learn what jobs pay your bills, which jobs you want to avoid, and your local service radius.",
    },
    {
      title: "Build & launch the campaign",
      body: "We set up keywords, negatives, ad copy, and call tracking. Ad spend is paid directly by you to Google.",
    },
    {
      title: "Measure calls & refine spend",
      body: "We review genuine phone calls and enquiries each week, cutting waste and scaling what works.",
    },
  ],
  aboutEyebrow: "About",
  aboutHeading: "The people behind the work.",
  aboutIntro:
    "Add a short, factual introduction to your team here.",
  founders: [
    {
      name: "",
      role: "Technical delivery",
      bio: "Google Ads campaign setup, search term filtering and call tracking, kept performing properly.",
      photoSrc: "",
    },
    {
      name: "",
      role: "Business development",
      bio: "Understanding your trade goals, keeping you updated, and making sure your phone rings with the right jobs.",
      photoSrc: "",
    },
  ],
  faqs: [
    {
      question: "Do I need a new website?",
      answer:
        "No. If your current website has a working phone number and contact form, we send traffic directly to your existing site. We are focused on Google Ads, not selling web redesigns.",
    },
    {
      question: "Is advertising spend included in agency fees?",
      answer:
        "No. You pay advertising spend directly to Google with your own card. Our management fee is separate, agreed in advance, and completely transparent.",
    },
    {
      question: "How do you measure results?",
      answer:
        "We track genuine phone calls and form enquiries generated by the campaign. We do not count 5-second wrong numbers or report vanity metrics like impressions.",
    },
    {
      question: "Which areas do you cover?",
      answer:
        "Set your service area here and describe where you actually work.",
    },
  ],
  contactHeading: "Get in touch.",
  contactBody:
    "Use the form to ask a question or describe your business. This template runs in mock mode until delivery is configured.",
  formSubmitLabel: "Send message",
} as const

export type SiteConfig = typeof site
